project:
  name: quickstart-r3-corda
  owner: quickstart-eng@amazon.com
  package_lambda: false
  regions:
  - ap-northeast-2
  - ap-southeast-2
  - eu-central-1
  - eu-west-1
  - us-east-1
  - us-east-2
  - us-west-2
  s3_bucket: ''
tests:
  corda:
    parameters:
      AvailabilityZones: $[taskcat_genaz_2]
      CordaAccessCIDR: 0.0.0.0/0
      CordaRPCAccessCIDR: 0.0.0.0/0
      CountryCode: GB
      DBMasterUserPassword: _$[taskcat_genpass_8A]
      DBMultiAZ: 'false'
      KeyPairName: $[taskcat_getkeypair]
      Location: London
      OneTimeKey: ''
      QSS3BucketName: $[taskcat_autobucket]
      QSS3KeyPrefix: quickstart-r3-corda/
      RemoteAccessCIDR: 0.0.0.0/0
      TestnetEndpoint: ''
      VPCCIDR: 10.0.0.0/16
    regions:
    - us-west-1
    - us-west-2
    - eu-west-1
    - ca-central-1
    - ap-northeast-1
    - ap-southeast-2
    - ap-southeast-1
    - ap-northeast-2
    - us-east-2
    - eu-west-2
    - eu-central-1
    template: templates/corda-master.template
